# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

set calc_order="bycols"
newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
let A0 = 7
let A1 = 1
let B1 = 2
let C1 = 3
let D1 = 4
let E1 = 5
let F1 = 6
let A2 = 1
let B2 = 2
let C2 = 3
let D2 = 4
let E2 = 5
let A3 = 1
let B3 = 2
let C3 = 3
let D3 = 3
let E3 = 4
let F3 = 5
let A4 = 1
let B4 = 2
let C4 = 3
let D4 = 4
let E4 = 4
let F4 = 5
let A5 = 1
let B5 = 2
let C5 = 3
let D5 = 3
let E5 = 3
let F5 = 4
let A6 = 1
let B6 = 2
let C6 = 2
let D6 = 3
let E6 = 4
let A7 = 1
let B7 = 2
let C7 = 2
let D7 = 2
let E7 = 3
let A8 = -7
let B8 = -4
let C8 = -3
let D8 = 1
let E8 = 2
let F8 = 3
let A20 = 1
let B20 = 10
let C20 = 4
let D20 = 7
let E20 = A20*C20
label G20 = "a"
let A21 = 2
let B21 = 20
let C21 = 5
let D21 = 8
let E21 = A21*C21
label G21 = "b"
let A22 = 3
let B22 = 30
let C22 = 6
let D22 = 9
let E22 = A22*C22
label G22 = "a"
let E23 = @sum(E20:E22)
goto E24
